<?php
$_lang['customurls'] = 'Custom URLs';
$_lang['customurls.menu_desc'] = 'Define your own alias and URI patterns';
$_lang['customurls.customurls_err_nf'] = 'Rule not found';
$_lang['customurls.customurls_err_ns'] = 'Rule not specified.';
$_lang['customurls.customurls_err_nfs'] = 'Rule not found or specified.';
$_lang['customurls.customurls_err_generate'] = 'An error occurred while trying to regenerate custom URLs.';
$_lang['customurls.customurls_err_remove'] = 'An error occurred while trying to remove the rule.';
$_lang['customurls.customurl_create'] = 'Add a rule';
$_lang['customurls.customurl_generate'] = 'Regenerate custom URLs';
$_lang['customurls.customurl_generate_confirm'] = 'Are you sure you want to regenerate custom URLs ? This will override existing custom rules.';
$_lang['customurls.customurl_update'] = 'Update';
$_lang['customurls.customurl_remove'] = 'Delete';
$_lang['customurls.customurl_remove_confirm'] = 'Are you sure you want to delete this rule ?';
$_lang['customurls.management'] = 'Custom URLs';
$_lang['customurls.management_desc'] = 'This extra allows you to define custom alias or URI patterns for your resources. It supports translit and Redirector packages. You can build your patterns from resource fields, TV, snippets and output filters and set some constraints like you\'d do with custom forms.For example, with CustomURLs you can add the resource\'s ID or publish month in the aliases of all resources or just for ones whose parent = 1 or template = 1. Documentation : http://rtfm.modx.com/display/ADDON/CustomUrls';
$_lang['customurls.pattern'] = 'Pattern';
$_lang['customurls.criteria_key'] = 'Constraint field';
$_lang['customurls.criteria_value'] = 'Constraint';
$_lang['customurls.usergroup'] = 'User group';
$_lang['customurls.uri'] = 'URI';
$_lang['customurls.override'] = 'Override';
$_lang['customurls.active'] = 'Active';